# TYPE  DATABASE        USER            ADDRESS                 METHOD

# 1. Cho phép kết nối nội bộ (Local)
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust

# 2. Cho phép Slave kết nối để đồng bộ (Replication)
# LƯU Ý: Thay 'replicator' bằng tên user bạn đã tạo trong .env
host    replication     replicator      0.0.0.0/0               scram-sha-256

# 3. Cho phép các ứng dụng kết nối vào Database
host    all             all             0.0.0.0/0               scram-sha-256