### Master pg_hba.conf for replication
### Update replication user if you change POSTGRESQL_REPLICATION_USER in compose/.env.

# TYPE  DATABASE       USER            ADDRESS                 METHOD
local   all             all                                     trust
host    all             all             0.0.0.0/0               md5
host    all             all             ::/0                    md5

# Allow the replica to connect for streaming replication
host    replication    replicator      0.0.0.0/0               md5
host    replication    replicator      ::/0                    md5

