# Cho phép kết nối từ mọi địa chỉ IP bên trong mạng Docker
listen_addresses = '*'

# Cấu hình cho Replication (Đồng bộ)
wal_level = replica          # Mức độ ghi log đủ để đồng bộ
max_wal_senders = 10         # Số lượng Slave tối đa có thể kết nối
max_replication_slots = 10   # Giữ lại các bản ghi log cho đến khi Slave nhận được
hot_standby = on             # Cho phép đọc dữ liệu trên Slave (nếu cần)